---
apiVersion: v1
kind: Namespace
metadata:
  name: platform-system
  labels:
    name: platform-system
    tier: system
    monitoring: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: platform-core
  labels:
    name: platform-core
    tier: application
    monitoring: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: platform-infra
  labels:
    name: platform-infra
    tier: infrastructure
    monitoring: enabled
